### ISSUE TITLE
Add Thorium Browser

### ISSUE THREAD

**Issue by BrycensRanch** [albertopasqualetto/browser-paths#2]
as the title says

it's a based fork of chromium becoming popular on gnu linux

**Comment by albertopasqualetto** [comment]
Sure! If you want, you can also create a PR by yourself.

**Comment by albertopasqualetto** [comment]
- [X] Linux support
- [ ] Windows support
- [ ] MacOs support

**Comment by albertopasqualetto** [comment]
@BrycensRanch Well, I added linux support in last version.
If you need or you want to contribute, you can also add the support for windows and macos.

**Comment by BrycensRanch** [comment]
Hi! Sorry for the slow response, yeah, I’ll be glad to contribute to this project. If all goes well, it should certainly be done this week.

**Comment by albertopasqualetto** [comment]
@BrycensRanch thanks!
